'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AlertCircle, ArrowRight, Banknote, CalendarClock, CheckCircle2, ClipboardCheck, FileText, RefreshCw, Save, TriangleAlert } from 'lucide-react';
import { CashFormValues, getTodayOverviewAction, saveCashReconciliationAction, saveShiftReportAction, ShiftReportValues } from '@/app/actions/shiftOperationsActions';

type Overview = Awaited<ReturnType<typeof getTodayOverviewAction>>['data'];
const currency = new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' });
const emptyCash: CashFormValues = { openingCash: 0, closingCash: 0, fiscalReport: 0, terminalReport: 0, blikReport: 0, cashToBag: 0, eventCash: 0, cashOperations: 0, operationsDescription: '', differenceDescription: '' };
const emptyReport: ShiftReportValues = { intensity: 'standard', incidents: '', equipmentNotes: '', stockNotes: '', handoverNotes: '' };

export default function TodayPage() {
  const [date] = useState(() => new Date().toISOString().slice(0, 10));
  const [overview, setOverview] = useState<Overview>(undefined);
  const [cash, setCash] = useState<CashFormValues>(emptyCash);
  const [report, setReport] = useState<ShiftReportValues>(emptyReport);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<'cash' | 'report' | null>(null); const [message, setMessage] = useState<string | null>(null);
  const load = async () => { setLoading(true); const result = await getTodayOverviewAction(date); if (result.success && result.data) { setOverview(result.data); const c = result.data.cash; if (c) setCash({ openingCash: c.openingCash, closingCash: c.closingCash, fiscalReport: c.fiscalReport, terminalReport: c.terminalReport, blikReport: c.blikReport, cashToBag: c.cashToBag, eventCash: c.eventCash, cashOperations: c.cashOperations, operationsDescription: c.operationsDescription || '', differenceDescription: c.differenceDescription || '' }); const r = result.data.report; if (r) setReport({ intensity: r.intensity, incidents: r.incidents || '', equipmentNotes: r.equipmentNotes || '', stockNotes: r.stockNotes || '', handoverNotes: r.handoverNotes || '' }); } else setMessage(result.error || 'Nie udało się pobrać danych.'); setLoading(false); };
  useEffect(() => {
    let active = true;
    void getTodayOverviewAction(date).then(result => {
      if (!active) return;
      if (result.success && result.data) {
        setOverview(result.data);
        const c = result.data.cash;
        if (c) setCash({ openingCash: c.openingCash, closingCash: c.closingCash, fiscalReport: c.fiscalReport, terminalReport: c.terminalReport, blikReport: c.blikReport, cashToBag: c.cashToBag, eventCash: c.eventCash, cashOperations: c.cashOperations, operationsDescription: c.operationsDescription || '', differenceDescription: c.differenceDescription || '' });
        const r = result.data.report;
        if (r) setReport({ intensity: r.intensity, incidents: r.incidents || '', equipmentNotes: r.equipmentNotes || '', stockNotes: r.stockNotes || '', handoverNotes: r.handoverNotes || '' });
      } else setMessage(result.error || 'Nie udało się pobrać danych.');
      setLoading(false);
    });
    return () => { active = false; };
  }, [date]);
  const calculated = Math.round(((cash.closingCash - cash.openingCash - cash.cashOperations) - (cash.fiscalReport - cash.terminalReport - cash.blikReport)) * 100) / 100;
  const updateCash = (field: keyof CashFormValues, value: string) => setCash(current => ({ ...current, [field]: typeof current[field] === 'number' ? Number(value) || 0 : value }));
  const saveCash = async (event: React.FormEvent) => { event.preventDefault(); setSaving('cash'); setMessage(null); const result = await saveCashReconciliationAction(date, cash); setSaving(null); setMessage(result.success ? `Rozliczenie zapisane. Kontrola: ${currency.format(result.checkAmount || 0)}` : result.error || 'Błąd zapisu.'); if (result.success) void load(); };
  const saveReport = async (event: React.FormEvent) => { event.preventDefault(); setSaving('report'); setMessage(null); const result = await saveShiftReportAction(date, report); setSaving(null); setMessage(result.success ? 'Raport zmiany zapisany.' : result.error || 'Błąd zapisu.'); if (result.success) void load(); };
  const checklistCard = (label: string, data: { total: number; done: number; problems: number } | undefined, href: string) => <Link href={href} className="glass-card p-5 rounded-2xl border border-white/10 hover:border-brand-gold/40 transition"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-wider text-[#888] font-bold">{label}</p><p className="text-xl font-black text-white mt-1">{data?.done || 0}<span className="text-[#666]"> / {data?.total || 0}</span></p></div><ClipboardCheck className="w-6 h-6 text-brand-gold" /></div>{(data?.problems || 0) > 0 && <p className="text-[11px] mt-3 text-brand-red flex items-center gap-1"><TriangleAlert className="w-3.5 h-3.5" />Problemów: {data?.problems}</p>}</Link>;
  return <div className="max-w-6xl mx-auto space-y-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-extrabold text-white font-display">PANEL <span className="text-brand-gold">DZISIAJ</span></h2><p className="text-xs text-[#a0a0a0] mt-1">{new Date(`${date}T12:00:00`).toLocaleDateString('pl-PL', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' })}</p></div><button onClick={load} className="p-2.5 rounded-lg bg-[#1a1a1a] text-brand-gold"><RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} /></button></div>
  {message && <div className="rounded-xl p-3 text-xs border border-brand-gold/25 bg-brand-gold/10 text-brand-gold flex gap-2"><AlertCircle className="w-4 h-4 shrink-0" />{message}</div>}
  <section className="grid md:grid-cols-4 gap-4">{checklistCard('Otwarcie', overview?.opening, '/checklists')}{checklistCard('Zamknięcie', overview?.closing, '/checklists')}<div className="glass-card p-5 rounded-2xl border border-white/10"><p className="text-[10px] uppercase tracking-wider text-[#888] font-bold">Kasa</p><p className={`text-lg font-black mt-2 ${overview?.cash ? (overview.cash.checkAmount === 0 ? 'text-green-400' : 'text-brand-red') : 'text-[#666]'}`}>{overview?.cash ? (overview.cash.checkAmount === 0 ? 'Zgodna' : currency.format(overview.cash.checkAmount)) : 'Do rozliczenia'}</p></div><div className="glass-card p-5 rounded-2xl border border-white/10"><p className="text-[10px] uppercase tracking-wider text-[#888] font-bold">Raport zmiany</p><p className={`text-lg font-black mt-2 ${overview?.report ? 'text-green-400' : 'text-[#666]'}`}>{overview?.report ? 'Zapisany' : 'Do uzupełnienia'}</p></div></section>
  {overview?.schedule && <section className="glass-card p-5 rounded-2xl border border-white/10"><div className="flex gap-3"><CalendarClock className="w-5 h-5 text-brand-gold" /><div><p className="text-sm font-bold text-white">Dzisiejsza zmiana {overview.schedule.isClosed ? '— lokal zamknięty' : `${overview.schedule.openTime || '—'}–${overview.schedule.closeTime || '—'}`}</p>{overview.schedule.eventRemarks && <p className="text-xs text-[#aaa] mt-1">Wydarzenie: {overview.schedule.eventRemarks}</p>}{overview.schedule.remarks && <p className="text-xs text-[#777] mt-1">{overview.schedule.remarks}</p>}</div></div></section>}
  <div className="grid lg:grid-cols-2 gap-6"><form onSubmit={saveCash} className="glass-card rounded-2xl border border-white/10 p-5 space-y-4"><h3 className="font-bold text-white flex items-center gap-2"><Banknote className="w-5 h-5 text-brand-gold" />Rozliczenie kasy</h3><p className="text-[11px] text-[#888]">Kontrola według obecnego arkusza Excel.</p><div className="grid grid-cols-2 gap-3">{([['openingCash','Start dnia'],['closingCash','Koniec dnia'],['fiscalReport','Raport fiskalny'],['terminalReport','Raport terminal'],['blikReport','Raport BLIK'],['cashToBag','Do woreczka'],['eventCash','Urodziny / wycieczki'],['cashOperations','Operacje gotówkowe']] as [keyof CashFormValues,string][]).map(([key,label]) => <label key={key} className="text-[11px] text-[#aaa]">{label}<input type="number" step="0.01" value={cash[key] as number} onChange={e => updateCash(key,e.target.value)} className="mt-1 w-full px-3 py-2 bg-[#0a0a0a] border border-white/10 rounded-lg text-sm text-white" /></label>)}</div><textarea value={cash.operationsDescription} onChange={e => updateCash('operationsDescription',e.target.value)} placeholder="Opis operacji gotówkowych" className="w-full min-h-16 p-3 bg-[#0a0a0a] border border-white/10 rounded-lg text-xs text-white" />{calculated !== 0 && <textarea required value={cash.differenceDescription} onChange={e => updateCash('differenceDescription',e.target.value)} placeholder="Wyjaśnienie różnicy — wymagane" className="w-full min-h-16 p-3 bg-brand-red/5 border border-brand-red/30 rounded-lg text-xs text-white" />}<div className={`p-3 rounded-lg text-sm font-bold ${calculated === 0 ? 'bg-green-500/10 text-green-400' : 'bg-brand-red/10 text-brand-red'}`}>Sprawdzenie danych: {currency.format(calculated)}</div><button disabled={saving === 'cash'} className="w-full py-2.5 rounded-lg bg-brand-gold text-[#151515] text-xs font-extrabold flex justify-center gap-2"><Save className="w-4 h-4" />{saving === 'cash' ? 'Zapisywanie…' : 'Zapisz rozliczenie'}</button></form>
  <form onSubmit={saveReport} className="glass-card rounded-2xl border border-white/10 p-5 space-y-4"><h3 className="font-bold text-white flex items-center gap-2"><FileText className="w-5 h-5 text-brand-gold" />Raport końca zmiany</h3><label className="text-[11px] text-[#aaa]">Intensywność dnia<select value={report.intensity} onChange={e => setReport(v => ({...v,intensity:e.target.value as ShiftReportValues['intensity']}))} className="mt-1 w-full px-3 py-2 bg-[#0a0a0a] border border-white/10 rounded-lg text-sm text-white"><option value="calm">Spokojnie</option><option value="standard">Standardowo</option><option value="busy">Bardzo intensywnie</option></select></label>{([['incidents','Incydenty / problemy z klientami'],['equipmentNotes','Usterki i sprzęt'],['stockNotes','Braki magazynowe'],['handoverNotes','Informacje dla kolejnej zmiany']] as [keyof ShiftReportValues,string][]).map(([key,label]) => <label key={key} className="block text-[11px] text-[#aaa]">{label}<textarea value={report[key] as string} onChange={e => setReport(v => ({...v,[key]:e.target.value}))} className="mt-1 w-full min-h-20 p-3 bg-[#0a0a0a] border border-white/10 rounded-lg text-xs text-white" /></label>)}<button disabled={saving === 'report'} className="w-full py-2.5 rounded-lg bg-brand-gold text-[#151515] text-xs font-extrabold flex justify-center gap-2"><CheckCircle2 className="w-4 h-4" />{saving === 'report' ? 'Zapisywanie…' : 'Zapisz raport zmiany'}</button></form></div><Link href="/checklists" className="text-xs text-brand-gold font-bold flex items-center gap-1">Przejdź do checklist <ArrowRight className="w-4 h-4" /></Link></div>;
}
